web:
  image: nginx:1.12
  ports:
    - "8082:80"
  volumes:
    - ./code:/code
    - ./nginx.conf/site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes: 
    - ./code:/code
  links:
    - maria

maria:
  image: mariadb:latest
  volumes:
  - ./install:/docker-entrypoint-initdb.d/
  ports:
    - 3307:3306
  environment: 
    MYSQL_ROOT_PASSWORD: azerty

